name: flutteraplicativo
description: Aplicativo Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter_masked_text: ^0.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  scoped_model: ^1.0.1
  splashscreen: ^1.3.5
  search_widget: ^1.0.2 
  intl: 
  provider: ^6.0.1
  pdf: ^3.6.3
  path_provider:
  flutter_launcher_icons: ^0.9.2
  checkbox_grouped: ^1.7.1
  cpf_cnpj_validator: ^2.0.0
  crypto: 
  hive: ^1.0.0
  hive_flutter: any
  sqflite:
  masked_text: ^0.0.6
  smart_select: ^4.3.2
  sticky_headers: "^0.1.8"
  open_file: ^3.2.1
  printing: ^5.3.0
  fluttertoast: ^7.1.1
  wc_form_validators: ^1.0.0
  image_picker: ^0.6.2
  image_cropper: ^1.4.1
  cached_network_image: ^2.5.1
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.11.1+7
  firebase_storage: ^3.0.2
  
  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.0.0
  hive_generator:
  build_runner:




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagens/01.png
    - assets/imagens/02.png
    - assets/imagens/03.png
    - assets/imagens/04.png
    - assets/imagens/login.gif
    - assets/imagens/cadastro.png
    - assets/imagens/excluir.png
    - assets/backgroud.jpeg
    - assets/backgroud2.jpeg
    - assets/logo1.png
    - assets/logocrt.jpeg
    - assets/2users.png
    - assets/cesta.png
    - assets/carrinho.png
    - assets/user.png
    - assets/settings.png
    - assets/carga.png
    - assets/CRTSISTEMAS.png
    - assets/pp.jpg
    - assets/addUser.png
    - assets/lupa.png
    - assets/editUser.png
    - assets/14377073000101.png
    - assets/25245917000168.png
    - assets/imagens/loading.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
     
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


analyzer:
  strong-mode: true
  language:
=======
name: flutteraplicativo
description: Aplicativo Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter_masked_text: ^0.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  scoped_model: ^1.0.1
  splashscreen: ^1.3.5
  search_widget: ^1.0.2 
  intl: 
  provider: ^6.0.1
  pdf: ^3.6.3
  path_provider:
  flutter_launcher_icons: ^0.9.2
  checkbox_grouped: ^1.7.1
  cpf_cnpj_validator: ^2.0.0
  crypto: 
  hive: ^1.0.0
  hive_flutter: any
  sqflite:
  masked_text: ^0.0.6
  smart_select: ^4.3.2
  sticky_headers: "^0.1.8"
  open_file: ^3.2.1
  printing: ^5.3.0
  fluttertoast: ^7.1.1
  wc_form_validators: ^1.0.0
  image_picker: ^0.6.2
  image_cropper: ^1.4.1
  cached_network_image: ^2.5.1
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.11.1+7
  firebase_storage: ^3.0.2
  
  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.0.0
  hive_generator:
  build_runner:




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagens/01.png
    - assets/imagens/02.png
    - assets/imagens/03.png
    - assets/imagens/04.png
    - assets/imagens/login.gif
    - assets/imagens/cadastro.png
    - assets/imagens/excluir.png
    - assets/backgroud.jpeg
    - assets/backgroud2.jpeg
    - assets/logo1.png
    - assets/logocrt.jpeg
    - assets/2users.png
    - assets/cesta.png
    - assets/carrinho.png
    - assets/user.png
    - assets/settings.png
    - assets/carga.png
    - assets/CRTSISTEMAS.png
    - assets/pp.jpg
    - assets/addUser.png
    - assets/lupa.png
    - assets/editUser.png
    - assets/14377073000101.png
    - assets/25245917000168.png
    - assets/imagens/loading.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
     
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
