// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'dart:convert';

import 'package:flutter/cupertino.dart';

class Especifica extends ChangeNotifier {
  int USUID;
  int LOCID;
  int CXNID;
  int UPECADCLIENTE;
  int UPECADEMPRESA;
  int UPEEXCLUIREMPRESA;
  int UPECADFORNECEDOR;
  int UPEEXCLUIRFORNECEDOR;
  int UPECADCENTROCUSTO;
  int UPEEXCLUIRCENTROCUSTO;
  int UPECADVENDEDOR;
  int UPEEXCLUIRVENDEDOR;
  int UPECADFORMAPAGAMENTO;
  int UPEEXCLUIRFORMAPAGAMENTO;
  int UPECADGRUPOS;
  int UPEEXCLUIRGRUPOS;
  int UPECADCAIXAS;
  int UPEEXCLUIRCAIXAS;
  int UPECADLOCALESTOQUE;
  int UPEEXCLUIRLOCALESTOQUE;
  int UPECADCLASSIFICACAOFISCAL;
  int UPEEXCLUIRCLASSIFICACAOFISCAL;
  int UPECADPRODUTOS;
  int UPEEXCLUIRPRODUTOS;
  int UPEEXCLUIRCLIENTE;
  int UPECADUNIDADES;
  int UPEEXCLUIRUNIDADES;
  int UPECONFIGURACOES;
  String UPEVALORVENDA;
  int UPECADFABRICANTES;
  int UPEEXCLUIRFABRICANTES;
  int UPECADCARTOES;
  int UPEEXCLUIRCARTOES;
  int UPECADTIPODOCUMENTO;
  int UPEEXCLUIRTIPODOCUMENTO;
  int UPECADPLANOCONTAS;
  int UPEEXCLUIRPLANOCONTAS;
  int UPEDESCONTOFINAL;
  int UPEPERCENTUALDESCONTO;
  int UPEALTERARCLIENTE;
  int UPEEXCLUIRORCAMENTO;
  int UPEALTERARORCAMENTO;
  int UPEALTERARPRODUTO;
  Especifica({
    this.USUID,
    this.LOCID,
    this.CXNID,
    this.UPECADCLIENTE,
    this.UPECADEMPRESA,
    this.UPEEXCLUIREMPRESA,
    this.UPECADFORNECEDOR,
    this.UPEEXCLUIRFORNECEDOR,
    this.UPECADCENTROCUSTO,
    this.UPEEXCLUIRCENTROCUSTO,
    this.UPECADVENDEDOR,
    this.UPEEXCLUIRVENDEDOR,
    this.UPECADFORMAPAGAMENTO,
    this.UPEEXCLUIRFORMAPAGAMENTO,
    this.UPECADGRUPOS,
    this.UPEEXCLUIRGRUPOS,
    this.UPECADCAIXAS,
    this.UPEEXCLUIRCAIXAS,
    this.UPECADLOCALESTOQUE,
    this.UPEEXCLUIRLOCALESTOQUE,
    this.UPECADCLASSIFICACAOFISCAL,
    this.UPEEXCLUIRCLASSIFICACAOFISCAL,
    this.UPECADPRODUTOS,
    this.UPEEXCLUIRPRODUTOS,
    this.UPEEXCLUIRCLIENTE,
    this.UPECADUNIDADES,
    this.UPEEXCLUIRUNIDADES,
    this.UPECONFIGURACOES,
    this.UPEVALORVENDA,
    this.UPECADFABRICANTES,
    this.UPEEXCLUIRFABRICANTES,
    this.UPECADCARTOES,
    this.UPEEXCLUIRCARTOES,
    this.UPECADTIPODOCUMENTO,
    this.UPEEXCLUIRTIPODOCUMENTO,
    this.UPECADPLANOCONTAS,
    this.UPEEXCLUIRPLANOCONTAS,
    this.UPEDESCONTOFINAL,
    this.UPEPERCENTUALDESCONTO,
    this.UPEALTERARCLIENTE,
    this.UPEEXCLUIRORCAMENTO,
    this.UPEALTERARORCAMENTO,
    this.UPEALTERARPRODUTO,
  });

  Especifica especifica;

  void setPerm(Especifica es) {
    this.especifica = es;
    notifyListeners();
  }

  Especifica getEspecifica() {
    return this.especifica;
  }

  void limparLista() {
    listValores.clear();
    notifyListeners();
  }

  List listValores = [];

  valoresVenda(String permissao) {
    for (int i = 0; i < permissao.length; i++) {
      var venda = permissao.codeUnitAt(i);
      var valor = i + 1;
      if (venda == 49) {
        listValores.add({"VENDA": "$valor"});
      }
    }

    notifyListeners();
  }

  Especifica copyWith({
    int USUID,
    int LOCID,
    int CXNID,
    int UPECADCLIENTE,
    int UPECADEMPRESA,
    int UPEEXCLUIREMPRESA,
    int UPECADFORNECEDOR,
    int UPEEXCLUIRFORNECEDOR,
    int UPECADCENTROCUSTO,
    int UPEEXCLUIRCENTROCUSTO,
    int UPECADVENDEDOR,
    int UPEEXCLUIRVENDEDOR,
    int UPECADFORMAPAGAMENTO,
    int UPEEXCLUIRFORMAPAGAMENTO,
    int UPECADGRUPOS,
    int UPEEXCLUIRGRUPOS,
    int UPECADCAIXAS,
    int UPEEXCLUIRCAIXAS,
    int UPECADLOCALESTOQUE,
    int UPEEXCLUIRLOCALESTOQUE,
    int UPECADCLASSIFICACAOFISCAL,
    int UPEEXCLUIRCLASSIFICACAOFISCAL,
    int UPECADPRODUTOS,
    int UPEEXCLUIRPRODUTOS,
    int UPEEXCLUIRCLIENTE,
    int UPECADUNIDADES,
    int UPEEXCLUIRUNIDADES,
    int UPECONFIGURACOES,
    int UPEVALORVENDA,
    int UPECADFABRICANTES,
    int UPEEXCLUIRFABRICANTES,
    int UPECADCARTOES,
    int UPEEXCLUIRCARTOES,
    int UPECADTIPODOCUMENTO,
    int UPEEXCLUIRTIPODOCUMENTO,
    int UPECADPLANOCONTAS,
    int UPEEXCLUIRPLANOCONTAS,
    int UPEDESCONTOFINAL,
    int UPEPERCENTUALDESCONTO,
    int UPEALTERARCLIENTE,
    int UPEEXCLUIRORCAMENTO,
    int UPEALTERARORCAMENTO,
    int UPEALTERARPRODUTO,
  }) {
    return Especifica(
      USUID: USUID ?? this.USUID,
      LOCID: LOCID ?? this.LOCID,
      CXNID: CXNID ?? this.CXNID,
      UPECADCLIENTE: UPECADCLIENTE ?? this.UPECADCLIENTE,
      UPECADEMPRESA: UPECADEMPRESA ?? this.UPECADEMPRESA,
      UPEEXCLUIREMPRESA: UPEEXCLUIREMPRESA ?? this.UPEEXCLUIREMPRESA,
      UPECADFORNECEDOR: UPECADFORNECEDOR ?? this.UPECADFORNECEDOR,
      UPEEXCLUIRFORNECEDOR: UPEEXCLUIRFORNECEDOR ?? this.UPEEXCLUIRFORNECEDOR,
      UPECADCENTROCUSTO: UPECADCENTROCUSTO ?? this.UPECADCENTROCUSTO,
      UPEEXCLUIRCENTROCUSTO:
          UPEEXCLUIRCENTROCUSTO ?? this.UPEEXCLUIRCENTROCUSTO,
      UPECADVENDEDOR: UPECADVENDEDOR ?? this.UPECADVENDEDOR,
      UPEEXCLUIRVENDEDOR: UPEEXCLUIRVENDEDOR ?? this.UPEEXCLUIRVENDEDOR,
      UPECADFORMAPAGAMENTO: UPECADFORMAPAGAMENTO ?? this.UPECADFORMAPAGAMENTO,
      UPEEXCLUIRFORMAPAGAMENTO:
          UPEEXCLUIRFORMAPAGAMENTO ?? this.UPEEXCLUIRFORMAPAGAMENTO,
      UPECADGRUPOS: UPECADGRUPOS ?? this.UPECADGRUPOS,
      UPEEXCLUIRGRUPOS: UPEEXCLUIRGRUPOS ?? this.UPEEXCLUIRGRUPOS,
      UPECADCAIXAS: UPECADCAIXAS ?? this.UPECADCAIXAS,
      UPEEXCLUIRCAIXAS: UPEEXCLUIRCAIXAS ?? this.UPEEXCLUIRCAIXAS,
      UPECADLOCALESTOQUE: UPECADLOCALESTOQUE ?? this.UPECADLOCALESTOQUE,
      UPEEXCLUIRLOCALESTOQUE:
          UPEEXCLUIRLOCALESTOQUE ?? this.UPEEXCLUIRLOCALESTOQUE,
      UPECADCLASSIFICACAOFISCAL:
          UPECADCLASSIFICACAOFISCAL ?? this.UPECADCLASSIFICACAOFISCAL,
      UPEEXCLUIRCLASSIFICACAOFISCAL:
          UPEEXCLUIRCLASSIFICACAOFISCAL ?? this.UPEEXCLUIRCLASSIFICACAOFISCAL,
      UPECADPRODUTOS: UPECADPRODUTOS ?? this.UPECADPRODUTOS,
      UPEEXCLUIRPRODUTOS: UPEEXCLUIRPRODUTOS ?? this.UPEEXCLUIRPRODUTOS,
      UPEEXCLUIRCLIENTE: UPEEXCLUIRCLIENTE ?? this.UPEEXCLUIRCLIENTE,
      UPECADUNIDADES: UPECADUNIDADES ?? this.UPECADUNIDADES,
      UPEEXCLUIRUNIDADES: UPEEXCLUIRUNIDADES ?? this.UPEEXCLUIRUNIDADES,
      UPECONFIGURACOES: UPECONFIGURACOES ?? this.UPECONFIGURACOES,
      UPEVALORVENDA: UPEVALORVENDA ?? this.UPEVALORVENDA,
      UPECADFABRICANTES: UPECADFABRICANTES ?? this.UPECADFABRICANTES,
      UPEEXCLUIRFABRICANTES:
          UPEEXCLUIRFABRICANTES ?? this.UPEEXCLUIRFABRICANTES,
      UPECADCARTOES: UPECADCARTOES ?? this.UPECADCARTOES,
      UPEEXCLUIRCARTOES: UPEEXCLUIRCARTOES ?? this.UPEEXCLUIRCARTOES,
      UPECADTIPODOCUMENTO: UPECADTIPODOCUMENTO ?? this.UPECADTIPODOCUMENTO,
      UPEEXCLUIRTIPODOCUMENTO:
          UPEEXCLUIRTIPODOCUMENTO ?? this.UPEEXCLUIRTIPODOCUMENTO,
      UPECADPLANOCONTAS: UPECADPLANOCONTAS ?? this.UPECADPLANOCONTAS,
      UPEEXCLUIRPLANOCONTAS:
          UPEEXCLUIRPLANOCONTAS ?? this.UPEEXCLUIRPLANOCONTAS,
      UPEDESCONTOFINAL: UPEDESCONTOFINAL ?? this.UPEDESCONTOFINAL,
      UPEPERCENTUALDESCONTO:
          UPEPERCENTUALDESCONTO ?? this.UPEPERCENTUALDESCONTO,
      UPEALTERARCLIENTE: UPEALTERARCLIENTE ?? this.UPEALTERARCLIENTE,
      UPEEXCLUIRORCAMENTO: UPEEXCLUIRORCAMENTO ?? this.UPEEXCLUIRORCAMENTO,
      UPEALTERARORCAMENTO: UPEALTERARORCAMENTO ?? this.UPEALTERARORCAMENTO,
      UPEALTERARPRODUTO: UPEALTERARPRODUTO ?? this.UPEALTERARPRODUTO,
    );
  }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'USUID': USUID,
      'LOCID': LOCID,
      'CXNID': CXNID,
      'UPECADCLIENTE': UPECADCLIENTE,
      'UPECADEMPRESA': UPECADEMPRESA,
      'UPEEXCLUIREMPRESA': UPEEXCLUIREMPRESA,
      'UPECADFORNECEDOR': UPECADFORNECEDOR,
      'UPEEXCLUIRFORNECEDOR': UPEEXCLUIRFORNECEDOR,
      'UPECADCENTROCUSTO': UPECADCENTROCUSTO,
      'UPEEXCLUIRCENTROCUSTO': UPEEXCLUIRCENTROCUSTO,
      'UPECADVENDEDOR': UPECADVENDEDOR,
      'UPEEXCLUIRVENDEDOR': UPEEXCLUIRVENDEDOR,
      'UPECADFORMAPAGAMENTO': UPECADFORMAPAGAMENTO,
      'UPEEXCLUIRFORMAPAGAMENTO': UPEEXCLUIRFORMAPAGAMENTO,
      'UPECADGRUPOS': UPECADGRUPOS,
      'UPEEXCLUIRGRUPOS': UPEEXCLUIRGRUPOS,
      'UPECADCAIXAS': UPECADCAIXAS,
      'UPEEXCLUIRCAIXAS': UPEEXCLUIRCAIXAS,
      'UPECADLOCALESTOQUE': UPECADLOCALESTOQUE,
      'UPEEXCLUIRLOCALESTOQUE': UPEEXCLUIRLOCALESTOQUE,
      'UPECADCLASSIFICACAOFISCAL': UPECADCLASSIFICACAOFISCAL,
      'UPEEXCLUIRCLASSIFICACAOFISCAL': UPEEXCLUIRCLASSIFICACAOFISCAL,
      'UPECADPRODUTOS': UPECADPRODUTOS,
      'UPEEXCLUIRPRODUTOS': UPEEXCLUIRPRODUTOS,
      'UPEEXCLUIRCLIENTE': UPEEXCLUIRCLIENTE,
      'UPECADUNIDADES': UPECADUNIDADES,
      'UPEEXCLUIRUNIDADES': UPEEXCLUIRUNIDADES,
      'UPECONFIGURACOES': UPECONFIGURACOES,
      'UPEVALORVENDA': UPEVALORVENDA,
      'UPECADFABRICANTES': UPECADFABRICANTES,
      'UPEEXCLUIRFABRICANTES': UPEEXCLUIRFABRICANTES,
      'UPECADCARTOES': UPECADCARTOES,
      'UPEEXCLUIRCARTOES': UPEEXCLUIRCARTOES,
      'UPECADTIPODOCUMENTO': UPECADTIPODOCUMENTO,
      'UPEEXCLUIRTIPODOCUMENTO': UPEEXCLUIRTIPODOCUMENTO,
      'UPECADPLANOCONTAS': UPECADPLANOCONTAS,
      'UPEEXCLUIRPLANOCONTAS': UPEEXCLUIRPLANOCONTAS,
      'UPEDESCONTOFINAL': UPEDESCONTOFINAL,
      'UPEPERCENTUALDESCONTO': UPEPERCENTUALDESCONTO,
      'UPEALTERARCLIENTE': UPEALTERARCLIENTE,
      'UPEEXCLUIRORCAMENTO': UPEEXCLUIRORCAMENTO,
      'UPEALTERARORCAMENTO': UPEALTERARORCAMENTO,
      'UPEALTERARPRODUTO': UPEALTERARPRODUTO,
    };
  }

  factory Especifica.fromMap(Map<String, dynamic> map) {
    return Especifica(
      USUID: int.parse(map['USUID']),
      LOCID: int.parse(map['LOCID']),
      CXNID: int.parse(map['CXNID']),
      UPECADCLIENTE: int.parse(map['UPECADCLIENTE']),
      UPECADEMPRESA: int.parse(map['UPECADEMPRESA']),
      UPEEXCLUIREMPRESA: int.parse(map['UPEEXCLUIREMPRESA']),
      UPECADFORNECEDOR: int.parse(map['UPECADFORNECEDOR']),
      UPEEXCLUIRFORNECEDOR: int.parse(map['UPEEXCLUIRFORNECEDOR']),
      UPECADCENTROCUSTO: int.parse(map['UPECADCENTROCUSTO']),
      UPEEXCLUIRCENTROCUSTO: int.parse(map['UPEEXCLUIRCENTROCUSTO']),
      UPECADVENDEDOR: int.parse(map['UPECADVENDEDOR']),
      UPEEXCLUIRVENDEDOR: int.parse(map['UPEEXCLUIRVENDEDOR']),
      UPECADFORMAPAGAMENTO: int.parse(map['UPECADFORMAPAGAMENTO']),
      UPEEXCLUIRFORMAPAGAMENTO: int.parse(map['UPEEXCLUIRFORMAPAGAMENTO']),
      UPECADGRUPOS: int.parse(map['UPECADGRUPOS']),
      UPEEXCLUIRGRUPOS: int.parse(map['UPEEXCLUIRGRUPOS']),
      UPECADCAIXAS: int.parse(map['UPECADCAIXAS']),
      UPEEXCLUIRCAIXAS: int.parse(map['UPEEXCLUIRCAIXAS']),
      UPECADLOCALESTOQUE: int.parse(map['UPECADLOCALESTOQUE']),
      UPEEXCLUIRLOCALESTOQUE: int.parse(map['UPEEXCLUIRLOCALESTOQUE']),
      UPECADCLASSIFICACAOFISCAL: int.parse(map['UPECADCLASSIFICACAOFISCAL']),
      UPEEXCLUIRCLASSIFICACAOFISCAL:
          int.parse(map['UPEEXCLUIRCLASSIFICACAOFISCAL']),
      UPECADPRODUTOS: int.parse(map['UPECADPRODUTOS']),
      UPEEXCLUIRPRODUTOS: int.parse(map['UPEEXCLUIRPRODUTOS']),
      UPEEXCLUIRCLIENTE: int.parse(map['UPEEXCLUIRCLIENTE']),
      UPECADUNIDADES: int.parse(map['UPECADUNIDADES']),
      UPEEXCLUIRUNIDADES: int.parse(map['UPEEXCLUIRUNIDADES']),
      UPECONFIGURACOES: int.parse(map['UPECONFIGURACOES']),
      UPEVALORVENDA: map['UPEVALORVENDA'],
      UPECADFABRICANTES: int.parse(map['UPECADFABRICANTES']),
      UPEEXCLUIRFABRICANTES: int.parse(map['UPEEXCLUIRFABRICANTES']),
      UPECADCARTOES: int.parse(map['UPECADCARTOES']),
      UPEEXCLUIRCARTOES: int.parse(map['UPEEXCLUIRCARTOES']),
      UPECADTIPODOCUMENTO: int.parse(map['UPECADTIPODOCUMENTO']),
      UPEEXCLUIRTIPODOCUMENTO: int.parse(map['UPEEXCLUIRTIPODOCUMENTO']),
      UPECADPLANOCONTAS: int.parse(map['UPECADPLANOCONTAS']),
      UPEEXCLUIRPLANOCONTAS: int.parse(map['UPEEXCLUIRPLANOCONTAS']),
      UPEDESCONTOFINAL: int.parse(map['UPEDESCONTOFINAL']),
      UPEPERCENTUALDESCONTO: int.parse(map['UPEPERCENTUALDESCONTO']),
      UPEALTERARCLIENTE: int.parse(map['UPEALTERARCLIENTE']),
      UPEEXCLUIRORCAMENTO: int.parse(map['UPEEXCLUIRORCAMENTO']),
      UPEALTERARORCAMENTO: int.parse(map['UPEALTERARORCAMENTO']),
      UPEALTERARPRODUTO: int.parse(map['UPEALTERARPRODUTO']),
    );
  }

  String toJson() => json.encode(toMap());

  factory Especifica.fromJson(String source) =>
      Especifica.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return 'Especifica(USUID: $USUID, LOCID: $LOCID, CXNID: $CXNID, UPECADCLIENTE: $UPECADCLIENTE, UPECADEMPRESA: $UPECADEMPRESA, UPEEXCLUIREMPRESA: $UPEEXCLUIREMPRESA, UPECADFORNECEDOR: $UPECADFORNECEDOR, UPEEXCLUIRFORNECEDOR: $UPEEXCLUIRFORNECEDOR, UPECADCENTROCUSTO: $UPECADCENTROCUSTO, UPEEXCLUIRCENTROCUSTO: $UPEEXCLUIRCENTROCUSTO, UPECADVENDEDOR: $UPECADVENDEDOR, UPEEXCLUIRVENDEDOR: $UPEEXCLUIRVENDEDOR, UPECADFORMAPAGAMENTO: $UPECADFORMAPAGAMENTO, UPEEXCLUIRFORMAPAGAMENTO: $UPEEXCLUIRFORMAPAGAMENTO, UPECADGRUPOS: $UPECADGRUPOS, UPEEXCLUIRGRUPOS: $UPEEXCLUIRGRUPOS, UPECADCAIXAS: $UPECADCAIXAS, UPEEXCLUIRCAIXAS: $UPEEXCLUIRCAIXAS, UPECADLOCALESTOQUE: $UPECADLOCALESTOQUE, UPEEXCLUIRLOCALESTOQUE: $UPEEXCLUIRLOCALESTOQUE, UPECADCLASSIFICACAOFISCAL: $UPECADCLASSIFICACAOFISCAL, UPEEXCLUIRCLASSIFICACAOFISCAL: $UPEEXCLUIRCLASSIFICACAOFISCAL, UPECADPRODUTOS: $UPECADPRODUTOS, UPEEXCLUIRPRODUTOS: $UPEEXCLUIRPRODUTOS, UPEEXCLUIRCLIENTE: $UPEEXCLUIRCLIENTE, UPECADUNIDADES: $UPECADUNIDADES, UPEEXCLUIRUNIDADES: $UPEEXCLUIRUNIDADES, UPECONFIGURACOES: $UPECONFIGURACOES, UPEVALORVENDA: $UPEVALORVENDA, UPECADFABRICANTES: $UPECADFABRICANTES, UPEEXCLUIRFABRICANTES: $UPEEXCLUIRFABRICANTES, UPECADCARTOES: $UPECADCARTOES, UPEEXCLUIRCARTOES: $UPEEXCLUIRCARTOES, UPECADTIPODOCUMENTO: $UPECADTIPODOCUMENTO, UPEEXCLUIRTIPODOCUMENTO: $UPEEXCLUIRTIPODOCUMENTO, UPECADPLANOCONTAS: $UPECADPLANOCONTAS, UPEEXCLUIRPLANOCONTAS: $UPEEXCLUIRPLANOCONTAS, UPEDESCONTOFINAL: $UPEDESCONTOFINAL, UPEPERCENTUALDESCONTO: $UPEPERCENTUALDESCONTO, UPEALTERARCLIENTE: $UPEALTERARCLIENTE, UPEEXCLUIRORCAMENTO: $UPEEXCLUIRORCAMENTO, UPEALTERARORCAMENTO: $UPEALTERARORCAMENTO, UPEALTERARPRODUTO: $UPEALTERARPRODUTO)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Especifica &&
        other.USUID == USUID &&
        other.LOCID == LOCID &&
        other.CXNID == CXNID &&
        other.UPECADCLIENTE == UPECADCLIENTE &&
        other.UPECADEMPRESA == UPECADEMPRESA &&
        other.UPEEXCLUIREMPRESA == UPEEXCLUIREMPRESA &&
        other.UPECADFORNECEDOR == UPECADFORNECEDOR &&
        other.UPEEXCLUIRFORNECEDOR == UPEEXCLUIRFORNECEDOR &&
        other.UPECADCENTROCUSTO == UPECADCENTROCUSTO &&
        other.UPEEXCLUIRCENTROCUSTO == UPEEXCLUIRCENTROCUSTO &&
        other.UPECADVENDEDOR == UPECADVENDEDOR &&
        other.UPEEXCLUIRVENDEDOR == UPEEXCLUIRVENDEDOR &&
        other.UPECADFORMAPAGAMENTO == UPECADFORMAPAGAMENTO &&
        other.UPEEXCLUIRFORMAPAGAMENTO == UPEEXCLUIRFORMAPAGAMENTO &&
        other.UPECADGRUPOS == UPECADGRUPOS &&
        other.UPEEXCLUIRGRUPOS == UPEEXCLUIRGRUPOS &&
        other.UPECADCAIXAS == UPECADCAIXAS &&
        other.UPEEXCLUIRCAIXAS == UPEEXCLUIRCAIXAS &&
        other.UPECADLOCALESTOQUE == UPECADLOCALESTOQUE &&
        other.UPEEXCLUIRLOCALESTOQUE == UPEEXCLUIRLOCALESTOQUE &&
        other.UPECADCLASSIFICACAOFISCAL == UPECADCLASSIFICACAOFISCAL &&
        other.UPEEXCLUIRCLASSIFICACAOFISCAL == UPEEXCLUIRCLASSIFICACAOFISCAL &&
        other.UPECADPRODUTOS == UPECADPRODUTOS &&
        other.UPEEXCLUIRPRODUTOS == UPEEXCLUIRPRODUTOS &&
        other.UPEEXCLUIRCLIENTE == UPEEXCLUIRCLIENTE &&
        other.UPECADUNIDADES == UPECADUNIDADES &&
        other.UPEEXCLUIRUNIDADES == UPEEXCLUIRUNIDADES &&
        other.UPECONFIGURACOES == UPECONFIGURACOES &&
        other.UPEVALORVENDA == UPEVALORVENDA &&
        other.UPECADFABRICANTES == UPECADFABRICANTES &&
        other.UPEEXCLUIRFABRICANTES == UPEEXCLUIRFABRICANTES &&
        other.UPECADCARTOES == UPECADCARTOES &&
        other.UPEEXCLUIRCARTOES == UPEEXCLUIRCARTOES &&
        other.UPECADTIPODOCUMENTO == UPECADTIPODOCUMENTO &&
        other.UPEEXCLUIRTIPODOCUMENTO == UPEEXCLUIRTIPODOCUMENTO &&
        other.UPECADPLANOCONTAS == UPECADPLANOCONTAS &&
        other.UPEEXCLUIRPLANOCONTAS == UPEEXCLUIRPLANOCONTAS &&
        other.UPEDESCONTOFINAL == UPEDESCONTOFINAL &&
        other.UPEPERCENTUALDESCONTO == UPEPERCENTUALDESCONTO &&
        other.UPEALTERARCLIENTE == UPEALTERARCLIENTE &&
        other.UPEEXCLUIRORCAMENTO == UPEEXCLUIRORCAMENTO &&
        other.UPEALTERARORCAMENTO == UPEALTERARORCAMENTO &&
        other.UPEALTERARPRODUTO == UPEALTERARPRODUTO;
  }

  @override
  int get hashCode {
    return USUID.hashCode ^
        LOCID.hashCode ^
        CXNID.hashCode ^
        UPECADCLIENTE.hashCode ^
        UPECADEMPRESA.hashCode ^
        UPEEXCLUIREMPRESA.hashCode ^
        UPECADFORNECEDOR.hashCode ^
        UPEEXCLUIRFORNECEDOR.hashCode ^
        UPECADCENTROCUSTO.hashCode ^
        UPEEXCLUIRCENTROCUSTO.hashCode ^
        UPECADVENDEDOR.hashCode ^
        UPEEXCLUIRVENDEDOR.hashCode ^
        UPECADFORMAPAGAMENTO.hashCode ^
        UPEEXCLUIRFORMAPAGAMENTO.hashCode ^
        UPECADGRUPOS.hashCode ^
        UPEEXCLUIRGRUPOS.hashCode ^
        UPECADCAIXAS.hashCode ^
        UPEEXCLUIRCAIXAS.hashCode ^
        UPECADLOCALESTOQUE.hashCode ^
        UPEEXCLUIRLOCALESTOQUE.hashCode ^
        UPECADCLASSIFICACAOFISCAL.hashCode ^
        UPEEXCLUIRCLASSIFICACAOFISCAL.hashCode ^
        UPECADPRODUTOS.hashCode ^
        UPEEXCLUIRPRODUTOS.hashCode ^
        UPEEXCLUIRCLIENTE.hashCode ^
        UPECADUNIDADES.hashCode ^
        UPEEXCLUIRUNIDADES.hashCode ^
        UPECONFIGURACOES.hashCode ^
        UPEVALORVENDA.hashCode ^
        UPECADFABRICANTES.hashCode ^
        UPEEXCLUIRFABRICANTES.hashCode ^
        UPECADCARTOES.hashCode ^
        UPEEXCLUIRCARTOES.hashCode ^
        UPECADTIPODOCUMENTO.hashCode ^
        UPEEXCLUIRTIPODOCUMENTO.hashCode ^
        UPECADPLANOCONTAS.hashCode ^
        UPEEXCLUIRPLANOCONTAS.hashCode ^
        UPEDESCONTOFINAL.hashCode ^
        UPEPERCENTUALDESCONTO.hashCode ^
        UPEALTERARCLIENTE.hashCode ^
        UPEEXCLUIRORCAMENTO.hashCode ^
        UPEALTERARORCAMENTO.hashCode ^
        UPEALTERARPRODUTO.hashCode;
  }
}
